util: Preprocessor.py: fix encoding mismatch
In some cases (depending on the machine's current locale setup),
python uses ascii instead of utf8, causing exceptions like this:

  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 107: ordinal not in range(128)

Python needs to be explicitly told to use utf8 when opening the
text files.

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>